name: SAR-C2QM
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.20
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - seaborn==0.12.2
  - scikit-learn==1.2.1
  - scikit-learn-intelex==2023.0.2
  - timm=1.0.11
  - pip:
    - pillow==9.5.0
    - albumentations==0.4.3
    - diffusers
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - invisible-watermark
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.19.2
    - torchmetrics==0.6.0
    - kornia==0.6
    - -e src/taming-transformers-master
    - tqdm==4.66.5
    - opencv-python==4.1.2.30
    - matplotlib==3.7.5
    - src/GDAL-3.2.3-cp38-cp38-win_amd64.whl
    - -e src/latent-diffusion-main
