model:
  base_learning_rate: 5.0e-7
  target: SAR_C2QM.models.autoencoder.c2q_autoencoder.AutoencoderKL_RHV_imp
  params:
    embed_dim: 9
    image_key: image_in
    data_name: img_XL
    lossconfig:
      target: SAR_C2QM.modules.c2q_loss.Autoencoder_loss
      params:
        kl_weight: 1.0e-6
        nll_weight: 1.0e-5

    ddconfig:
      double_z: True
      z_channels: 9
      resolution: 256
      in_channels: 12
      out_ch: 12
      ch: 64
      ch_mult: [ 1,2,4 ]
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0


data:
  target: main_C2Q.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 0
    train:
      target: SAR_C2QM.data.c2q_real_ds.RealNumPyDataset_Atec
      params:
        ds_dir: data/250403_c2q_RHV_GF3_MultiWaveCode
        flag_ds: 0
        flag_data: img_XL
        flag_aug: False
    validation:
      target: SAR_C2QM.data.c2q_real_ds.RealNumPyDataset_Atec
      params:
        ds_dir: data/250403_c2q_RHV_GF3_MultiWaveCode
        flag_ds: 1
        flag_data: img_XL
        flag_aug: False

lightning:
  callbacks:
    image_logger:
      target: main_C2Q.ImageLogger
      params:
        epoch_frequency: 1
        max_images: 8

  trainer:
    benchmark: True
    # accumulate_grad_batches: 2
    accelerator: gpu
    gpus: 0,
    max_epochs: 50

  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      filename: "best_model"
      save_last: True
      monitor: "val/loss"
      save_top_k: 1
  
